//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int Id { get; set; }
        public int PartnerTypeId { get; set; }
        public int PartnerNameId { get; set; }
        public string DirectorSurname { get; set; }
        public string DirectorName { get; set; }
        public string DirectorPatronym { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string AdressIndex { get; set; }
        public int AdressRegionId { get; set; }
        public int AdressCityId { get; set; }
        public int AdressStreetId { get; set; }
        public int AdressHouseNum { get; set; }
        public string ITN { get; set; }
        public int Rating { get; set; }
    
        public virtual City City { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
        public virtual PartnerType PartnerType { get; set; }
        public virtual Region Region { get; set; }
        public virtual Street Street { get; set; }
    }
}
